### ISSUE TITLE
node index.js error

### ISSUE THREAD

**Issue by AbhinavGopal** [thakkarparth007/copilot-inspector#6]
Cloned, then did npm install, then node index.js.

Received the following error:
```Error handling module 8348
/Users/abhinavg/Documents/copilot-explorer/index.js:471
                    throw e;
                    ^

TypeError: Cannot read properties of undefined (reading 'getCode')
    at NodePath.getSource (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/path/introspection.js:154:27)
    at UnaryExpression (/Users/abhinavg/Documents/copilot-explorer/index.js:231:35)
    at NodePath._call (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/path/context.js:84:31)
    at TraversalContext.visitQueue (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitSingle (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:72:19)
    at TraversalContext.visit (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:121:19)
    at traverseNode (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/path/context.js:90:52)
    at TraversalContext.visitQueue (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitMultiple (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:67:17)
    at TraversalContext.visit (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:119:19)
    at traverseNode (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/path/context.js:90:52)
    at TraversalContext.visitQueue (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitMultiple (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:67:17)
    at TraversalContext.visit (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:119:19)
    at traverseNode (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/path/context.js:90:52)
    at TraversalContext.visitQueue (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitSingle (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:72:19)
    at TraversalContext.visit (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:121:19)
    at traverseNode (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/path/context.js:90:52)
    at TraversalContext.visitQueue (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitSingle (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:72:19)
    at TraversalContext.visit (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:121:19)
    at traverseNode (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/path/context.js:90:52)
    at TraversalContext.visitQueue (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitMultiple (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:67:17)
    at TraversalContext.visit (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:119:19)
    at traverseNode (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/path/context.js:90:52)
    at TraversalContext.visitQueue (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitSingle (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:72:19)
    at TraversalContext.visit (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:121:19)
    at traverseNode (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/path/context.js:90:52)
    at TraversalContext.visitQueue (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitMultiple (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:67:17)
    at TraversalContext.visit (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:119:19)
    at traverseNode (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/path/context.js:90:52)
    at TraversalContext.visitQueue (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitSingle (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:72:19)
    at TraversalContext.visit (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/context.js:121:19)
    at traverseNode (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/abhinavg/Documents/copilot-explorer/node_modules/@babel/traverse/lib/path/context.js:90:52)```

**Comment by thakkarparth007** [comment]
Thanks for raising the issue. This shouldn't happen now. I did a fresh install and verified that `node index.js` followed by `python codeviz/app.py` works.
